 drop table if exists product;
 create table product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO product(name, price) VALUES ('product1', 10000);
INSERT INTO product(name, price) VALUES ('product2', 20000);
